export const SOCKET_EVENTS = {
    ON_CONNECT: "on_connect",
    GET_ALL_FRIENDS: "get_all_friends",
    GET_ALL_MESSAGES: "get_all_messages",
    GET_ALL_ROOMS: "get_all_rooms",
    GET_ALL_ROOM_NOTIFICATIONS: "get_all_notifications",
    ADD_FRIEND: "add_friend",
    SEND_MESSAGE: "send_message",
    DELETE_MESSAGES: "delete_messages",
    READ_MESSAGES: "read_messages",
    FORWARD_MESSAGES: "forward_messages",
    REPLY_TO_MESSAGE: "reply_to_message",
    CREATE_ROOM: "create_room",
    INVITE_TO_ROOM: "invite_to_room",
    ACCEPT_INVITE_TO_JOIN_ROOM: "accept_invite_to_join_room",
    ERROR: "connect_error",
    ON_DISCONNECT: "on_disconnect",
};
