export const SOCKET_EVENTS = {
    ON_CONNECT: "connection",
    GET_ALL_FRIENDS: "get_all_friends",
    GET_ALL_MESSAGES: "get_all_messages",
    GET_ALL_ROOMS: "get_all_rooms",
    ADD_FRIEND: "add_friend",
    SEND_MESSAGE: "send_message",
    DELETE_MESSAGES: "delete_messages",
    READ_MESSAGES: "read_messages",
    FORWARD_MESSAGES: "forward_messages",
    REPLY_TO_MESSAGE: "reply_to_message",
    CREATE_ROOM: "create_room",
    INVITE_TO_ROOM: "invite_to_room",
    CONNECT_TO_ROOM: "connect_to_room",
    ACCEPT_INVITE_TO_JOIN_ROOM: "accept_invite_to_join_room",
    GET_ALL_ROOM_NOTIFICATIONS: "get_all_notifications",
    ON_INIT_USER: "on_connect",
    ON_DEINIT_USER: "on_disconnect",
    ON_DISCONNECT: "disconnecting",
};
